from datetime import timedelta


class IRedisBaseRepository:
    def get_instance(self, key: str) -> bytes | str | None: ...

    def set_instance(
        self, key: str, value: bytes | str | None, expire_time: int | timedelta = None
    ) -> None: ...

    def delete_instance(self, key: str) -> None: ...

    def delete_by_prefix(self, prefix: str) -> None: ...

    def check_existance(self, key: str) -> bool: ...
